### ISSUE TITLE
Change custom file and move around object?

### ISSUE THREAD

**Issue by SuperDuperMartin** [HippoAR/react-native-arkit#10]
Hi!
I have 2 questions!
Is it possible to change ARKit.Model file and render a different object? 
is it possible to move around the object?

![image](https://user-images.githubusercontent.com/8627696/29671311-79c38d02-88e9-11e7-84ea-7f3724f3da86.png)

i try to set different states here, but no rerender is done...

**Comment by macrozone** [comment]
Hi 

1. updating props seems not to work on the current npm version of react-native-arkit. It's solved in develop, but not published yet. Try my fork in the meantime: `yarn add @panter/react-native-arkit`. The fork contains current develop and new features (see my Pull requests)
2. with the above version, it should be possible to update the position, but i did not try it. I will soon try to implement dragging myself.

**Comment by SuperDuperMartin** [comment]
@macrozone thank you! ill give your pr a try!

**Comment by SuperDuperMartin** [comment]
@macrozone have you tried moving object? i cant get it to work...

**Comment by macrozone** [comment]
@SuperDuperMartin Can you try @panter/react-native-arkit@0.2.0 ? 

not every Object type had a proper update function. I now added it to every object. 

It's not optimized yet, because it removes the node from the scene and readds it, so its not really smooth, but this can be improved later.

**Comment by SuperDuperMartin** [comment]
@macrozone thank you for that! I got panResponder to work!

**Comment by SuperDuperMartin** [comment]
@macrozone you seem to know alot about this! do you know if planeDetection is working? and how to implement it?

**Comment by macrozone** [comment]
@SuperDuperMartin:

yes planedetection works. 

It basically detects horizontal plane on your arscene. You have to wait a bit, until it has found good planes though. You can visualize them by using onPlaneDetected and onPlaneUpdated.

After that, you can intersect rays from the camera (e.g. a touch point on the view) with these planes on the arscene to determine where on the screen the user has clicked and e.g. place something there.

Here is the basic api, e.g. by using events from panresponder. (in my case i needed to substract the offset of the arview (layout), because its not fullscreen in my case):

```
  ARKit.hitTestPlanes(
    {
                  x: gestureState.x0 - this.props.layout.x,
                  y: gestureState.y0 - this.props.layout.y,
    },
    ARKit.ARHitTestResultType.ExistingPlane
  ).then(({results}) => console.log(results))
```

please see https://github.com/panter/react-native-arkit/#static-methods

**Comment by macrozone** [comment]
I think the issue is resolved
