### ISSUE TITLE
No view appearing

### ISSUE THREAD

**Issue by GeekRishabh** [HippoAR/react-native-arkit#11]
![screen shot 2017-08-25 at 7 12 44 pm](https://user-images.githubusercontent.com/23093075/29716565-7005af44-89c9-11e7-83e0-a0700a36bcae.png)

getting this 
can anyone help ??

**Comment by greis** [comment]
Simulator doesn't work, only the following actual devices: iPhone 6s/7/SE, iPad 2017/Pro

**Comment by GeekRishabh** [comment]
@greis  the same view is in iphone also

**Comment by jamonholmgren** [comment]
iPhone 6 doesn't work @GeekRishabh , have to have an A9 processor or higher.

**Comment by macrozone** [comment]
I can reproduce this problem on a iphone 7.

It happens on first mount of the view. If i unmount it and remount it (e.g. by navigation), the view usually appears (but not always)

**Comment by qftgtr** [comment]
My guess is the size of the ar view is not properly set when first mount. When a React Native component is mounted its size starts from (0,0) and RN will calculate the right size from the stylesheet and automatically set it. Maybe I'm doing something wrong so the size is still (0,0) and nothing appears. I used [`layoutSubviews`](https://github.com/HippoAR/react-native-arkit/blob/master/ios/RCTARKit.m#L75) but it doesn't work all the time.

**Comment by macrozone** [comment]
@qftgtr strange thing is, that if you use the view-inspector of xcode, the view looks correct, altough its still white on the device

**Comment by macrozone** [comment]
ok i found out, that this error happens if you access any method of ARKit before the view is mounted. 

And because i introduced

```
componentWillMount() {
    ARKitManager.clearScene();
  }
```

this now happens every time. Without that line it seems to work...

I have to review that anyway. But in general, accessing ARKit(Manager) before any view is rendered should be possible. Maybe you access some constants or what ever.

Or view separate these things from the view itself
