### ISSUE TITLE
[Question] Render AR object only after scaning a specific picture / shape

### ISSUE THREAD

**Issue by stajics** [HippoAR/react-native-arkit#124]
The task i am trying to complete is to render a simple object in AR view but only after scanning a specific picture or a shape. For example scanning a red triangle on a pice of paper would render a shape above it.

Can somebody with more experience in AR point me on how hard / easy (or possible) that is? Not looking for a implementation , just a general guideline.

**Comment by macrozone** [comment]
This sounds like marker-based ar, which is not supported directly by arkit.

There are some 3rd party library that support marker-based ar, but i don't know any react-native version .

We would need an extension that analyzes every frame for some defined shapes and give their position and perspective

**Comment by bnjm** [comment]
You could use CoreML for this, see https://twitter.com/marlanag11/status/928008533676908544. Not sure if there are any efforts to bring that to react-native, but here's a cool open source project showing how to combine CoreML and ARKit: https://github.com/hanleyweng/CoreML-in-ARKit

Otherwise you would use something like OpenCV. Again, not sure if it's been done with react-native but would be cool to see that in action!

**Comment by macrozone** [comment]
@stajics , @bnjm arkit 1.5. seems to bring this feature! https://developer.apple.com/arkit/

**Comment by macrozone** [comment]
"Real world images, such as signs, posters, and artwork can be integrated into the AR experience"

**Comment by macrozone** [comment]
This is now possible with react-native-arkit 0.9.0-beta.4, but needs also beta version of xcode.
