### ISSUE TITLE
Can't build release

### ISSUE THREAD

**Issue by flexy1994** [HippoAR/react-native-arkit#41]
At creating a release build i get the following error:

_**No such file or directory: '/Users/felixbader/Library/Developer/Xcode/DerivedData/arTest-fvhvkgbiibenhyajvimoqvcjtjsv/Build/Products/Release-iphoneos/libRCTARKit.a'**_

Tested with a new project with React-Native 0.47.0 iOS 11 on iPhone 7. 
xCode 9

**Comment by macrozone** [comment]
@flexy1994 can you verify with the manual installation? https://github.com/HippoAR/react-native-arkit#manual-installation

check if

- project is included in Libraries in xcode
- libRCTARKit.a is in "Link Binary With Libraries"

**Comment by Tamiyadd** [comment]
I'm having the same issue also following the manual installation guide 😢

**Comment by rpiwetz** [comment]
I was able to fix this issue by making sure that "Valid Architectures" only had the "arm64" value.
Check for this in "Build Settings" -> "Architectures" -> "Valid Architectures" (I had to remove arm7 and arm7s values)
I had to make this change in two places...MyAppName's Build Settings as well as MyAppNameTests' Build Settings

Perhaps this change should occur automatically as a part of adding this library to the project since it only works for 64 bit architectures?

**Comment by macrozone** [comment]
@rpiwetz when i started with the project i also had many different build problems. Then, you try different things and some solve it and some make it worse, so its sometimes hard to find the underlying problem ;-) In particular if you lack experience on ios projects like i do.

E.g. on my project i still have armv7 and armv7s architecture and it builds fine.

The main problem on my project was, that it was built with expo and then ejected. Then it will use cocoapods for react-native dependencies. This can lead to header file missing errors on most third-party libraries. The fix is to adjust the Header Search paths on the library project.

But if you search on github for that error, you find tons of suggestions what to do. Some will lead to other problems.

If you have any build error, its best to follow the manual installation and revert any change you did. If  you then have an error, google for that. If the solution found leads to another error, it was probably the wrong solution ;-)

**Comment by XavierColombel** [comment]
Hey, `Debug` and `Release` values should be set to `YES` in **Project > Architectures > Build Active Architecture Only**. You shouldn't have to remove `armv7` and `armv7s`.

![Build Active Architecture Only](https://img15.hostingpics.net/pics/639092Capturedecran20171222a195241.png)

**Comment by macrozone** [comment]
I closes this because it was inactive. If you still have problem with the build, please head over to the slack channel react-native-ar.slack.com

**Comment by abdulhameedalyousef** [comment]
Lookup @Ben Flynn answer in https://stackoverflow.com/questions/26031932/cant-link-with-a-main-executable-file for help
