### ISSUE TITLE
Invalid package name "_PocketSVG"

### ISSUE THREAD

**Issue by twosmalltrees** [HippoAR/react-native-arkit#99]
Hey there, 

First off thanks for your work on this project! Unfortunately I'm having problems when following along with the manual instructions. I'm assuming the manual install still requires `npm install react-native-arkit --save` to be run initially? 

Unfortunately for me this is producing an error, seemingly due to the inclusion of pocketSVG in the dependencies - `invalid package name "_PocketSVG": name cannot start with an underscore`. 

Any thoughts on how to get around this?

**Comment by macrozone** [comment]
Hi @twosmalltrees. I "abused" npm to define the dependency to a non-npm package "PocketSVG". This works in yarn version 1, not sure if it works with npm as well. With which npm version did you try to install it? or with what yarn version? (i recommend yarn anyway, because it is much faster)

In react-native 0.50.0 we can use cocoapods to resolve dependency, so this hack is no longer needed.

**Comment by twosmalltrees** [comment]
Thanks for the quick response - I'm using yarn, but turns out my version was quite out of date. After updating to yarn v1.2.1 everything works as expected 😄 Cheers!
